// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for io_gsram.
//!
//! 'Unified GSRAM address map (2 MiB at 0x6100_0000).'

pub const IO_GSRAM_BASE: u32 = 0x61000000;
pub const BOOT_STATUS_OFFSET: u32 = 0x7000;
pub const IPC_ADMIN_HSM_RX_PI_OFFSET: u32 = 0x7004;
pub const IPC_ADMIN_HSM_RX_CI_OFFSET: u32 = 0x7008;
pub const IPC_ADMIN_HSM_TX_PI_OFFSET: u32 = 0x700C;
pub const IPC_ADMIN_HSM_TX_CI_OFFSET: u32 = 0x7010;
pub const ICQ_TAIL_SHADOW_OFFSET: u32 = 0xEF40;
pub const OCQ_TAIL_SHADOW_OFFSET: u32 = 0xF560;
pub const GDMA_CQ_TAIL_SHADOW_OFFSET: u32 = 0x13240;
pub const IPC_ADMIN_HSM_RX_RING_OFFSET: u32 = 0x7014;
pub const IPC_ADMIN_HSM_RX_RING_COUNT: u32 = 2;
pub const IPC_ADMIN_HSM_RX_RING_STRIDE: u32 = 0x40;
pub const IPC_ADMIN_HSM_TX_RING_OFFSET: u32 = 0x7094;
pub const IPC_ADMIN_HSM_TX_RING_COUNT: u32 = 2;
pub const IPC_ADMIN_HSM_TX_RING_STRIDE: u32 = 0x40;
pub const ISQ_OFFSET: u32 = 0xE440;
pub const ISQ_COUNT: u32 = 32;
pub const ISQ_STRIDE: u32 = 0x08;
pub const ICQ_OFFSET: u32 = 0xE540;
pub const ICQ_COUNT: u32 = 32;
pub const ICQ_STRIDE: u32 = 0x10;
pub const IO_SQ_OFFSET: u32 = 0xE740;
pub const IO_SQ_COUNT: u32 = 32;
pub const IO_SQ_STRIDE: u32 = 0x40;
pub const OSQ_OFFSET: u32 = 0xEF60;
pub const OSQ_COUNT: u32 = 32;
pub const OSQ_STRIDE: u32 = 0x10;
pub const OCQ_OFFSET: u32 = 0xF160;
pub const OCQ_COUNT: u32 = 32;
pub const OCQ_STRIDE: u32 = 0x10;
pub const IO_CQ_OFFSET: u32 = 0xF360;
pub const IO_CQ_COUNT: u32 = 32;
pub const IO_CQ_STRIDE: u32 = 0x10;
pub const GDMA_SQ_OFFSET: u32 = 0x12840;
pub const GDMA_SQ_COUNT: u32 = 32;
pub const GDMA_SQ_STRIDE: u32 = 0x40;
pub const GDMA_CQ_OFFSET: u32 = 0x13040;
pub const GDMA_CQ_COUNT: u32 = 32;
pub const GDMA_CQ_STRIDE: u32 = 0x10;
pub const AES_CMD_OFFSET: u32 = 0x15064;
pub const AES_CMD_COUNT: u32 = 32;
pub const AES_CMD_STRIDE: u32 = 0x18;
pub const UPKA_ENGINE_CMD_OFFSET: u32 = 0x15364;
pub const UPKA_ENGINE_CMD_COUNT: u32 = 16;
pub const UPKA_ENGINE_CMD_STRIDE: u32 = 0x14;
pub const SHA_CMD_OFFSET: u32 = 0x154A4;
pub const SHA_CMD_COUNT: u32 = 32;
pub const SHA_CMD_STRIDE: u32 = 0x20;
pub const IO_META_OFFSET: u32 = 0x20C58;
pub const IO_META_COUNT: u32 = 32;
pub const IO_META_STRIDE: u32 = 0x08;
pub const SRAM_IO_BUF_OFFSET: u32 = 0x20D58;
pub const SRAM_IO_BUF_COUNT: u32 = 32;
pub const SRAM_IO_BUF_STRIDE: u32 = 0x4800;
pub const SRAM_IO_BUF_SIZE: u32 = 0x4800;
pub const PART_STORE_OFFSET: u32 = 0xBB000;
pub const PART_STORE_COUNT: u32 = 1;
pub const PART_STORE_STRIDE: u32 = 0x30C00;
pub const PART_STORE_SIZE: u32 = 0x30C00;

tock_registers::register_bitfields! [u32,
    /// 'HSM boot phase indicator. Written by HSM firmware, polled by Admin. Values: 0=NotStarted, 1=Done, 2=Run.'
    pub BOOT_STATUS [
        STATE OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Producer or consumer index for an IPC ring.'
    pub IPC_ADMIN_HSM_RX_PI [
        VAL OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Producer or consumer index for an IPC ring.'
    pub IPC_ADMIN_HSM_RX_CI [
        VAL OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Producer or consumer index for an IPC ring.'
    pub IPC_ADMIN_HSM_TX_PI [
        VAL OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Producer or consumer index for an IPC ring.'
    pub IPC_ADMIN_HSM_TX_CI [
        VAL OFFSET(0) NUMBITS(32) [],
    ],
    /// 'DMA shadow of a queue producer/consumer index.'
    pub ICQ_TAIL_SHADOW [
        VAL OFFSET(0) NUMBITS(32) [],
    ],
    /// 'DMA shadow of a queue producer/consumer index.'
    pub OCQ_TAIL_SHADOW [
        VAL OFFSET(0) NUMBITS(32) [],
    ],
    /// 'DMA shadow of a queue producer/consumer index.'
    pub GDMA_CQ_TAIL_SHADOW [
        VAL OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Inbound Completion Queue info: status and interface select.'
    pub ICQ_INFO [
        STATUS OFFSET(0) NUMBITS(8) [],
        IFC_SLCT OFFSET(8) NUMBITS(8) [],
        RSVD OFFSET(16) NUMBITS(16) [],
    ],
    /// 'ISQ slot index being completed.'
    pub ICQ_INDEX [
        INDEX OFFSET(0) NUMBITS(16) [],
        RSVD OFFSET(16) NUMBITS(16) [],
    ],
    /// 'Outbound descriptor: queue IDs and credits.'
    pub OSQ_DESC [
        RX_QUEUE_ID OFFSET(0) NUMBITS(8) [],
        RX_CREDIT OFFSET(8) NUMBITS(8) [],
        TX_QUEUE_ID OFFSET(16) NUMBITS(8) [],
        AXI_ID OFFSET(24) NUMBITS(8) [],
    ],
    /// '16-bit tag + control field.'
    pub OSQ_TAG [
        TAG OFFSET(0) NUMBITS(16) [],
        CONTROL OFFSET(16) NUMBITS(16) [],
    ],
    /// 'Outbound Completion Queue info.'
    pub OCQ_INFO [
        STATUS OFFSET(0) NUMBITS(8) [],
        RSVD OFFSET(8) NUMBITS(24) [],
    ],
    /// '16-bit tag + status echoed from the OSQ entry.'
    pub OCQ_TAG [
        TAG OFFSET(0) NUMBITS(16) [],
        STATUS OFFSET(16) NUMBITS(8) [],
        RSVD OFFSET(24) NUMBITS(8) [],
    ],
    /// 'GDMA completion status and tag.'
    pub GDMA_CQ_STATUS [
        TAG OFFSET(0) NUMBITS(16) [],
        SUCCESS OFFSET(16) NUMBITS(1) [],
        RSVD OFFSET(17) NUMBITS(15) [],
    ],
    /// 'Controller ID for this IO slot.'
    pub IO_META_CTLR [
        CONTROLLER_ID OFFSET(0) NUMBITS(16) [],
        RSVD OFFSET(16) NUMBITS(16) [],
    ],
    /// 'Queue ID and index for this IO slot.'
    pub IO_META_QUEUE [
        QUEUE_ID OFFSET(0) NUMBITS(16) [],
        QUEUE_INDEX OFFSET(16) NUMBITS(16) [],
    ]
];

/// Regfile entry struct for `ipc_message`.
#[repr(C)]
pub struct IpcMessage {
    pub dw0: crate::RW<u32>,
    pub dw1: crate::RW<u32>,
    pub dw2: crate::RW<u32>,
    pub dw3: crate::RW<u32>,
    pub dw4: crate::RW<u32>,
    pub dw5: crate::RW<u32>,
    pub dw6: crate::RW<u32>,
    pub dw7: crate::RW<u32>,
    pub dw8: crate::RW<u32>,
    pub dw9: crate::RW<u32>,
    pub dw10: crate::RW<u32>,
    pub dw11: crate::RW<u32>,
    pub dw12: crate::RW<u32>,
    pub dw13: crate::RW<u32>,
    pub dw14: crate::RW<u32>,
    pub dw15: crate::RW<u32>,
}

/// Regfile entry struct for `isq_entry`.
#[repr(C)]
pub struct IsqEntry {
    pub addr_lo: crate::RW<u32>,
    pub addr_hi: crate::RW<u32>,
}

/// Regfile entry struct for `icq_entry`.
#[repr(C)]
pub struct IcqEntry {
    pub addr_lo: crate::RW<u32>,
    pub addr_hi: crate::RW<u32>,
    pub info: crate::RW<u32, ICQ_INFO::Register>,
    pub index: crate::RW<u32, ICQ_INDEX::Register>,
}

/// Regfile entry struct for `io_sq_entry`.
#[repr(C)]
pub struct IoSqEntry {
    pub dw0: crate::RW<u32>,
    pub dw1: crate::RW<u32>,
    pub dw2: crate::RW<u32>,
    pub dw3: crate::RW<u32>,
    pub dw4: crate::RW<u32>,
    pub dw5: crate::RW<u32>,
    pub dw6: crate::RW<u32>,
    pub dw7: crate::RW<u32>,
    pub dw8: crate::RW<u32>,
    pub dw9: crate::RW<u32>,
    pub dw10: crate::RW<u32>,
    pub dw11: crate::RW<u32>,
    pub dw12: crate::RW<u32>,
    pub dw13: crate::RW<u32>,
    pub dw14: crate::RW<u32>,
    pub dw15: crate::RW<u32>,
}

/// Regfile entry struct for `osq_entry`.
#[repr(C)]
pub struct OsqEntry {
    pub addr_lo: crate::RW<u32>,
    pub addr_hi: crate::RW<u32>,
    pub desc: crate::RW<u32, OSQ_DESC::Register>,
    pub tag: crate::RW<u32, OSQ_TAG::Register>,
}

/// Regfile entry struct for `ocq_entry`.
#[repr(C)]
pub struct OcqEntry {
    pub addr_lo: crate::RW<u32>,
    pub addr_hi: crate::RW<u32>,
    pub info: crate::RW<u32, OCQ_INFO::Register>,
    pub tag: crate::RW<u32, OCQ_TAG::Register>,
}

/// Regfile entry struct for `io_cq_entry`.
#[repr(C)]
pub struct IoCqEntry {
    pub dw0: crate::RW<u32>,
    pub dw1: crate::RW<u32>,
    pub dw2: crate::RW<u32>,
    pub dw3: crate::RW<u32>,
}

/// Regfile entry struct for `gdma_sq_entry`.
#[repr(C)]
pub struct GdmaSqEntry {
    pub dw0: crate::RW<u32>,
    pub dw1: crate::RW<u32>,
    pub dw2: crate::RW<u32>,
    pub dw3: crate::RW<u32>,
    pub dw4: crate::RW<u32>,
    pub dw5: crate::RW<u32>,
    pub dw6: crate::RW<u32>,
    pub dw7: crate::RW<u32>,
    pub dw8: crate::RW<u32>,
    pub dw9: crate::RW<u32>,
    pub dw10: crate::RW<u32>,
    pub dw11: crate::RW<u32>,
    pub dw12: crate::RW<u32>,
    pub dw13: crate::RW<u32>,
    pub dw14: crate::RW<u32>,
    pub dw15: crate::RW<u32>,
}

/// Regfile entry struct for `gdma_cq_entry`.
#[repr(C)]
pub struct GdmaCqEntry {
    pub status: crate::RW<u32, GDMA_CQ_STATUS::Register>,
    pub rsvd0: crate::RW<u32>,
    pub rsvd1: crate::RW<u32>,
    pub rsvd2: crate::RW<u32>,
}

/// Regfile entry struct for `aes_cmd_entry`.
#[repr(C)]
pub struct AesCmdEntry {
    pub cmd_code: crate::RW<u32>,
    pub result: crate::RW<u32>,
    pub byte_count: crate::RW<u32>,
    pub message: crate::RW<u32>,
    pub key: crate::RW<u32>,
    pub iv: crate::RW<u32>,
}

/// Regfile entry struct for `upka_cmd_entry`.
#[repr(C)]
pub struct UpkaCmdEntry {
    pub command_code: crate::RW<u32>,
    pub result_addr: crate::RW<u32>,
    pub arg1_addr: crate::RW<u32>,
    pub arg2_addr: crate::RW<u32>,
    pub arg3_addr: crate::RW<u32>,
}

/// Regfile entry struct for `sha_cmd_entry`.
#[repr(C)]
pub struct ShaCmdEntry {
    pub sha_command: crate::RW<u32>,
    pub sha_result: crate::RW<u32>,
    pub sha_msg_addr: crate::RW<u32>,
    pub sha_msg_len: crate::RW<u32>,
    pub sha_init_digest: crate::RW<u32>,
    pub sha_key_addr: crate::RW<u32>,
    pub pass_msg_buff: crate::RW<u32>,
    pub sha_key_len: crate::RW<u32>,
}

/// Regfile entry struct for `io_meta_entry`.
#[repr(C)]
pub struct IoMetaEntry {
    pub ctlr: crate::RW<u32, IO_META_CTLR::Register>,
    pub queue: crate::RW<u32, IO_META_QUEUE::Register>,
}

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub IoGsramRegs {
            (0x0 => _reserved0),
            (0x7000 => pub boot_status: crate::RW<u32, super::BOOT_STATUS::Register>),
            (0x7004 => pub ipc_admin_hsm_rx_pi: crate::RW<u32, super::IPC_ADMIN_HSM_RX_PI::Register>),
            (0x7008 => pub ipc_admin_hsm_rx_ci: crate::RW<u32, super::IPC_ADMIN_HSM_RX_CI::Register>),
            (0x700c => pub ipc_admin_hsm_tx_pi: crate::RW<u32, super::IPC_ADMIN_HSM_TX_PI::Register>),
            (0x7010 => pub ipc_admin_hsm_tx_ci: crate::RW<u32, super::IPC_ADMIN_HSM_TX_CI::Register>),
            (0x7014 => pub ipc_admin_hsm_rx_ring: [super::IpcMessage; 2]),
            (0x7094 => pub ipc_admin_hsm_tx_ring: [super::IpcMessage; 2]),
            (0x7114 => _reserved1),
            (0xe440 => pub isq: [super::IsqEntry; 32]),
            (0xe540 => pub icq: [super::IcqEntry; 32]),
            (0xe740 => pub io_sq: [super::IoSqEntry; 32]),
            (0xef40 => pub icq_tail_shadow: crate::RW<u32, super::ICQ_TAIL_SHADOW::Register>),
            (0xef44 => _reserved2),
            (0xef60 => pub osq: [super::OsqEntry; 32]),
            (0xf160 => pub ocq: [super::OcqEntry; 32]),
            (0xf360 => pub io_cq: [super::IoCqEntry; 32]),
            (0xf560 => pub ocq_tail_shadow: crate::RW<u32, super::OCQ_TAIL_SHADOW::Register>),
            (0xf564 => _reserved3),
            (0x12840 => pub gdma_sq: [super::GdmaSqEntry; 32]),
            (0x13040 => pub gdma_cq: [super::GdmaCqEntry; 32]),
            (0x13240 => pub gdma_cq_tail_shadow: crate::RW<u32, super::GDMA_CQ_TAIL_SHADOW::Register>),
            (0x13244 => _reserved4),
            (0x15064 => pub aes_cmd: [super::AesCmdEntry; 32]),
            (0x15364 => pub upka_engine_cmd: [super::UpkaCmdEntry; 16]),
            (0x154a4 => pub sha_cmd: [super::ShaCmdEntry; 32]),
            (0x158a4 => _reserved5),
            (0x20c58 => pub io_meta: [super::IoMetaEntry; 32]),
            (0x20d58 => pub sram_io_buf: [u8; 589824]),
            (0xb0d58 => _reserved6),
            (0xbb000 => pub part_store: [u8; 199680]),
            (0xebc00 => @END),
        }
    }
}
