// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for key_vault_table_t.
//!
//! 'One 17408-byte vault table: metadata + bitmap + blob.'

pub const KEY_VAULT_TABLE_T_BASE: u32 = 0x000EBC00;
pub const BITMAP_OFFSET: u32 = 0x800;
pub const ENTRY_OFFSET: u32 = 0x00;
pub const ENTRY_COUNT: u32 = 256;
pub const ENTRY_STRIDE: u32 = 0x08;
pub const BLOB_OFFSET: u32 = 0x900;
pub const BLOB_COUNT: u32 = 1;
pub const BLOB_STRIDE: u32 = 0x3B00;
pub const BLOB_SIZE: u32 = 0x3B00;

tock_registers::register_bitfields! [u32,
    /// '32 blob-block occupancy bits.'
    pub BITMAP [
        BITS OFFSET(0) NUMBITS(32) [],
    ],
    /// 'PhysicalEntry low DWORD: blob block offset + flags.'
    pub PHYSICAL_DW0 [
        OFFSET OFFSET(0) NUMBITS(16) [],
        DISABLED OFFSET(16) NUMBITS(1) [],
        SESSION OFFSET(17) NUMBITS(1) [],
        FLAGS_RSVD OFFSET(18) NUMBITS(14) [],
    ],
    /// 'PhysicalEntry high DWORD: session id / key tag, kind, app id.'
    pub PHYSICAL_DW1 [
        SESSION_OR_TAG OFFSET(0) NUMBITS(16) [],
        KIND OFFSET(16) NUMBITS(8) [],
        APP_ID OFFSET(24) NUMBITS(8) [],
    ]
];

/// Regfile entry struct for `physical_entry`.
#[repr(C)]
pub struct PhysicalEntry {
    pub dw0: crate::RW<u32, PHYSICAL_DW0::Register>,
    pub dw1: crate::RW<u32, PHYSICAL_DW1::Register>,
}

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub KeyVaultTableTRegs {
            (0x0 => pub entry: [super::PhysicalEntry; 256]),
            (0x800 => pub bitmap: [crate::RW<u32, super::BITMAP::Register>; 64]),
            (0x900 => pub blob: [u8; 15104]),
            (0x4400 => @END),
        }
    }
}
