// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for sha.
//!
//! 'HS-SHA secure hash accelerator (single instance) supporting SHA-1, SHA-256, SHA-384, SHA-512. Descriptor-driven dispatch model identical to UPKA. Base address 0xA040_0000 -- confirm against silicon RDL when available.'

pub const SHA_BASE: u32 = 0xA0400000;
pub const COMMAND_OFFSET: u32 = 0x00;
pub const STATUS_OFFSET: u32 = 0x04;

tock_registers::register_bitfields! [u32,
    /// 'Descriptor doorbell. Writing this register triggers the engine to fetch the 8-DWORD ShaCommandDesc descriptor located at the written AXI address (GSRAM only -- DTCM is NOT reachable by the SHA AXI master) and start executing the requested operation. The descriptor must be 4-byte aligned and remain valid until STATUS reports completion.'
    pub COMMAND [
        /// 'AXI address of the ShaCommandDesc descriptor in GSRAM. Reads return the last-written value (not consumed by hardware on read). Writes act as the doorbell that triggers the engine to fetch the descriptor.'
        DESC_ADDR OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Engine status. Polled by firmware between submit and completion; latched by the engine on every state transition. A Done or Error IRQ fires on every command completion (positive and negative).'
    pub STATUS [
        /// 'Engine is currently processing a command. Cleared on completion (success or error). Firmware must NOT write the COMMAND register while BUSY is set.'
        BUSY OFFSET(0) NUMBITS(1) [],
        /// 'Engine successfully finished the most recent command. Mutually exclusive with the ERROR_* bits. STATUS is read-only; this bit is cleared by hardware when the next command's doorbell sets BUSY (firmware must NOT write STATUS).'
        COMPLETE OFFSET(1) NUMBITS(1) [],
        /// 'Engine could not decode the command structure successfully (invalid opcode, bad descriptor layout).'
        ERROR_CMD OFFSET(2) NUMBITS(1) [],
        /// 'Engine encountered an error initiating an AXI bus transaction (e.g. SLVERR / DECERR on a result, message buffer, or descriptor fetch).'
        ERROR_BUS OFFSET(3) NUMBITS(1) [],
        /// 'Engine detected an internal fault while working on the operation (parity, lane-fault, or engine-fault).'
        ERROR_FAULT OFFSET(4) NUMBITS(1) [],
        /// 'Engine is/was working on a command initiated by a different bus master than the one reading the STATUS register. Driver masks this bit out of completion decode (mirrors UPKA pattern).'
        NOT_OWNER OFFSET(5) NUMBITS(1) [],
        /// 'Reference digest matched the computed digest for the last command. Only meaningful when the descriptor was submitted with command_code.check_digest set; for plain digest operations this bit is ignored.'
        DIGEST_MATCH OFFSET(6) NUMBITS(1) [],
        RSVD_0 OFFSET(7) NUMBITS(25) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub ShaRegs {
            (0x0 => pub command: crate::RW<u32, super::COMMAND::Register>),
            (0x4 => pub status: crate::RO<u32, super::STATUS::Register>),
            (0x8 => @END),
        }
    }
}
