# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
edition = "2024"
name = "azihsm_ossl_engine_core"
publish = false
version = "0.1.0"

[features]
default = []
engine = [
  "azihsm_ossl_engine_sys/engine",
  "dep:parking_lot",
  "dep:thiserror",
  "dep:tracing",
  "dep:zeroize",
]

[dependencies]
azihsm_ossl_engine_sys.workspace = true
parking_lot = { optional = true, workspace = true }
thiserror = { optional = true, workspace = true }
tracing = { optional = true, workspace = true }
zeroize = { optional = true, workspace = true }

[lints]
workspace = true
