# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
[package]
edition = "2024"
name = "azihsm_sdk_fuzz"
publish = false
version = "0.0.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
azihsm_crypto = { path = "../crates/crypto" }
azihsm_ddi = { path = "../ddi/lib" }
azihsm_ddi_emu = { optional = true, path = "../ddi/emu" }
azihsm_ddi_interface = { path = "../ddi/interface" }
azihsm_ddi_tbor_codec = { path = "../ddi/tbor/codec" }
azihsm_ddi_tbor_test_harness = { path = "../crates/tbor_test_harness" }
azihsm_ddi_tbor_types = { path = "../ddi/tbor/types" }
azihsm_session_ex_crypto = { path = "../crates/session_ex_crypto" }
x509 = { path = "../crates/x509" }
zerocopy = { version = "0.8.17" }

# dependencies for fuzzing
libfuzzer-sys = { features = ["arbitrary-derive"], version = "0.4" }

[features]
default = []
emu = ["azihsm_ddi/emu", "azihsm_ddi_tbor_test_harness/emu"]

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_request_round_trip"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_request_round_trip.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_request_view"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_request_view.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_response_round_trip"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_response_round_trip.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_response_view"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_response_view.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_session_open_round_trip"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_session_open_round_trip.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_psk_change"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_psk_change.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_part_init"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_part_init.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_part_final"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_part_final.rs"
test = false
