# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
[package]
edition = "2024"
name = "azihsm_sdk_fuzz"
publish = false
version = "0.0.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
azihsm_ddi_tbor_codec = { path = "../ddi/tbor/codec" }

# dependencies for fuzzing
libfuzzer-sys = { features = ["arbitrary-derive"], version = "0.4" }

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_request_round_trip"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_request_round_trip.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_request_view"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_request_view.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_response_round_trip"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_response_round_trip.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_response_view"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_response_view.rs"
test = false
