# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

language = "C"

header = "/*\n * Copyright (c) Microsoft Corporation.\n * Licensed under the MIT License.\n */"

cpp_compat = true

include_guard = "AZIHSM_API_H"

documentation_style = "c"

# Codegen Options

# When generating a C header, the kind of declaration style to use for structs
# or enums.
#
# possible values:
# * "type": typedef struct { ... } MyType;
# * "tag": struct MyType { ... };
# * "both": typedef struct MyType { ... } MyType;
#
# default: "both"
style = "tag"

# If this option is true `usize` and `isize` will be converted into `size_t` and `ptrdiff_t`
# instead of `uintptr_t` and `intptr_t` respectively.
usize_is_size_t = true

[export]

# A list of items to not include in the generated bindings
# default: []
exclude = ["AzihsmWideChar"]
include = [
  "AzihsmAlgoAesCbcParams",
  "AzihsmAlgoAesGcmParams",
  "AzihsmAlgoAesXtsParams",
  "AzihsmAlgoEcdhParams",
  "AzihsmAlgoHkdfParams",
  "AzihsmAlgoKbkdfCounterParams",
  "AzihsmAlgoRsaAesKeyWrapParams",
  "AzihsmAlgoRsaAesWrapParams",
  "AzihsmAlgoRsaPkcsOaepParams",
  "AzihsmAlgoRsaPkcsPssParams",
  "AzihsmMobkCallbackOps",
  "AzihsmPotaCallbackOps",
  "AzihsmResiliencyConfig",
  "AzihsmResiliencyLockOps",
  "AzihsmResiliencyStorageOps",
  "AzihsmSdCertChain",
  "AzihsmSdCreatePeerBackupParams",
  "AzihsmSdCreateRemoteBackupParams",
  "AzihsmSdEvidence",
  "AzihsmSdResealRemoteBackupParams",
  "AzihsmSdRestoreLocalBackupParams",
  "AzihsmSdRestorePeerBackupParams",
  "AzihsmSdRestoreRemoteBackupParams",
  "AzihsmSessExPartFinalParams",
  "AzihsmSessExPartInitParams",
  "AzihsmSessionPsk",
  "HsmEccCurve",
  "HsmError",
  "HsmKeyClass",
  "HsmKeyKind",
  "HsmPartType",
]

item_types = [
  "constants",
  "enums",
  "functions",
  "opaque",
  "structs",
  "typedefs",
]

[export.rename]
"AES_GCM_IV_SIZE" = "AZIHSM_AES_GCM_IV_SIZE"
"AES_GCM_TAG_SIZE" = "AZIHSM_AES_GCM_TAG_SIZE"
"AzihsmAlgo" = "azihsm_algo"
"AzihsmAlgoAesCbcParams" = "azihsm_algo_aes_cbc_params"
"AzihsmAlgoAesGcmParams" = "azihsm_algo_aes_gcm_params"
"AzihsmAlgoAesXtsParams" = "azihsm_algo_aes_xts_params"
"AzihsmAlgoEcdhParams" = "azihsm_algo_ecdh_params"
"AzihsmAlgoHkdfParams" = "azihsm_algo_hkdf_params"
"AzihsmAlgoId" = "azihsm_algo_id"
"AzihsmAlgoKbkdfCounterParams" = "azihsm_algo_kbkdf_counter_params"
"AzihsmAlgoRsaAesKeyWrapParams" = "azihsm_algo_rsa_aes_key_wrap_params"
"AzihsmAlgoRsaAesWrapParams" = "azihsm_algo_rsa_aes_wrap_params"
"AzihsmAlgoRsaPkcsOaepParams" = "azihsm_algo_rsa_pkcs_oaep_params"
"AzihsmAlgoRsaPkcsPssParams" = "azihsm_algo_rsa_pkcs_pss_params"
"AzihsmApiRev" = "azihsm_api_rev"
"AzihsmBuffer" = "azihsm_buffer"
"AzihsmChar" = "azihsm_char"
"AzihsmCredentials" = "azihsm_credentials"
"AzihsmEccCurve" = "azihsm_ecc_curve"
"AzihsmHandle" = "azihsm_handle"
"AzihsmKeyClass" = "azihsm_key_class"
"AzihsmKeyKind" = "azihsm_key_kind"
"AzihsmKeyProp" = "azihsm_key_prop"
"AzihsmKeyPropId" = "azihsm_key_prop_id"
"AzihsmKeyPropList" = "azihsm_key_prop_list"
"AzihsmMgf1Id" = "azihsm_mgf1_id"
"AzihsmMobkCallbackOps" = "azihsm_mobk_callback_ops"
"AzihsmOwnerBackupKeyConfig" = "azihsm_owner_backup_key_config"
"AzihsmOwnerBackupKeySource" = "azihsm_owner_backup_key_source"
"AzihsmPartInfo" = "azihsm_part_info"
"AzihsmPartPolicyBuilder" = "azihsm_part_policy_builder"
"AzihsmPartProp" = "azihsm_part_prop"
"AzihsmPartPropId" = "azihsm_part_prop_id"
"AzihsmPartType" = "azihsm_part_type"
"AzihsmPotaCallbackOps" = "azihsm_pota_callback_ops"
"AzihsmPotaEndorsement" = "azihsm_pota_endorsement"
"AzihsmPotaEndorsementData" = "azihsm_pota_endorsement_data"
"AzihsmPotaEndorsementSource" = "azihsm_pota_endorsement_source"
"AzihsmResiliencyConfig" = "azihsm_resiliency_config"
"AzihsmResiliencyLockOps" = "azihsm_resiliency_lock_ops"
"AzihsmResiliencyStorageOps" = "azihsm_resiliency_storage_ops"
"AzihsmSdCertChain" = "azihsm_sd_cert_chain"
"AzihsmSdCreatePeerBackupParams" = "azihsm_sd_create_peer_backup_params"
"AzihsmSdCreateRemoteBackupParams" = "azihsm_sd_create_remote_backup_params"
"AzihsmSdEvidence" = "azihsm_sd_evidence"
"AzihsmSdResealRemoteBackupParams" = "azihsm_sd_reseal_remote_backup_params"
"AzihsmSdRestoreLocalBackupParams" = "azihsm_sd_restore_local_backup_params"
"AzihsmSdRestorePeerBackupParams" = "azihsm_sd_restore_peer_backup_params"
"AzihsmSdRestoreRemoteBackupParams" = "azihsm_sd_restore_remote_backup_params"
"AzihsmSessExPartFinalParams" = "azihsm_sess_ex_part_final_params"
"AzihsmSessExPartInitParams" = "azihsm_sess_ex_part_init_params"
"AzihsmSessionExType" = "azihsm_session_ex_type"
"AzihsmSessionProp" = "azihsm_session_prop"
"AzihsmSessionPropId" = "azihsm_session_prop_id"
"AzihsmSessionPsk" = "azihsm_session_psk"
"AzihsmStatus" = "azihsm_status"
"AzihsmStr" = "azihsm_str"
"HsmEccCurve" = "azihsm_ecc_curve"
"HsmError" = "azihsm_status"
"HsmKeyClass" = "azihsm_key_class"
"HsmKeyKind" = "azihsm_key_kind"
"HsmOwnerBackupKeySource" = "azihsm_owner_backup_key_source"
"HsmPartType" = "azihsm_part_type"
"HsmPotaEndorsementSource" = "azihsm_pota_endorsement_source"
"HsmSessionExType" = "azihsm_session_ex_type"
"PSK_LEN" = "AZIHSM_PSK_LEN"

[defines]
"target_os = linux" = "__linux__ "
"target_os = windows" = "_WIN32"

[enum]
enum_class = false
rename_variants = "QualifiedScreamingSnakeCase"
