// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

#![no_std]

//! X.509 certificate and CSR builder for AZIHSM (`no_std`).
//!
//! This crate constructs DER-encoded X.509 certificates and PKCS#10 CSRs
//! at runtime by patching variable fields into pre-generated TBS
//! (To-Be-Signed) templates and signing the result with ECDSA-P384
//! through the [`HsmCrypto`](azihsm_fw_hsm_pal_traits::HsmCrypto) PAL.
//!
//! The approach is inspired by Caliptra's x509 crate: a generator tool
//! (Linux-only, OpenSSL-based) creates valid certificates with known
//! placeholder byte patterns, then the runtime patches variable fields
//! at known offsets and assembles the final DER document.
//!
//! # API shape
//!
//! All public builders ([`cert_builder::build_root_cert`],
//! [`cert_builder::build_leaf_cert`], [`csr_builder::build_csr`])
//! follow the same async query/copy contract as
//! [`azihsm_fw_core_crypto_key_report::key_report`]:
//!
//! ```ignore
//! pub async fn build_X<'a, P>(
//!     pal: &P,
//!     io: &impl HsmIo,
//!     alloc: &'a impl HsmScopedAlloc,
//!     params: &XParams<'_>,
//!     priv_key: &DmaBuf,
//!     out: Option<&mut [u8]>,
//! ) -> HsmResult<usize>
//! where P: HsmCrypto + HsmAlloc + 'a;
//! ```
//!
//! `out: None` runs in **query mode** and returns the worst-case
//! upper-bound output size without touching the PAL.  `out: Some(buf)`
//! runs in **copy mode**, computes the SHA-384 digest of the patched
//! TBS, asks the PAL to ECDSA-P384-sign it, DER-encodes the
//! signature, and writes the complete DER document into
//! `buf[..returned]`.  The returned size in copy mode is the actual
//! number of bytes written (≤ the query-mode size; the difference
//! depends on whether the signature's `r` / `s` values needed DER
//! sign-bit padding).
//!
//! # Architecture
//!
//! - **Templates** (`root_cert`, `leaf_cert`, `csr`): Auto-generated
//!   Rust modules containing `const` TBS byte arrays with placeholder
//!   bytes (`0x5F`) at variable field positions, plus `const`
//!   offset/length values for each field.
//!
//! - **Builders** (`cert_builder`, `csr_builder`): Async functions
//!   that allocate DMA scratch via the supplied
//!   [`HsmScopedAlloc`](azihsm_fw_hsm_pal_traits::HsmScopedAlloc),
//!   patch the chosen TBS template, drive
//!   [`HsmHash`](azihsm_fw_hsm_pal_traits::HsmHash) and
//!   [`HsmEcc`](azihsm_fw_hsm_pal_traits::HsmEcc) on it, and assemble
//!   the final DER document.
//!
//! - **DER helpers** (`der_helpers`): Low-level DER encoding routines
//!   for length fields, INTEGERs, and ECDSA signatures.
//!
//! # Template Generation
//!
//! Templates are regenerated by the
//! `azihsm_fw_core_crypto_x509_builder_gen` tool:
//!
//! ```sh
//! cargo run -p azihsm_fw_core_crypto_x509_builder_gen
//! ```
//!
//! The generator only builds on Linux and requires OpenSSL.
//!
//! # Supported document types
//!
//! | Type | Module | Extensions |
//! |------|--------|------------|
//! | Root CA (self-signed) | [`root_cert`] | BasicConstraints(CA:TRUE), KeyUsage(keyCertSign+cRLSign), SKI |
//! | Leaf (end-entity) | [`leaf_cert`] | BasicConstraints(CA:FALSE), KeyUsage(variable), SKI, AKI |
//! | CSR (PKCS#10) | [`csr`] | Subject DN only (CN + serialNumber) |

/// Runtime certificate builder for Root CA and Leaf certificates.
pub mod cert_builder;

/// Runtime CSR (PKCS#10 CertificationRequest) builder.
pub mod csr_builder;

/// Low-level DER encoding helpers for ECDSA signatures and length fields.
pub mod der_helpers;

/// Subject field padding helpers (caller-specified target length).
pub mod padding;

// Auto-generated template modules (regenerated by
// `azihsm_fw_core_crypto_x509_builder_gen`).

/// CSR (PKCS#10) TBS template — auto-generated.
pub mod csr;

/// Leaf (end-entity) certificate TBS template — auto-generated.
pub mod leaf_cert;

/// Root CA (self-signed) certificate TBS template — auto-generated.
pub mod root_cert;
