// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Raw FFI bindings to the OpenSSL 1.1.x ENGINE API.
//!
//! Auto-generated by bindgen from `wrapper.h` on Linux when built with the
//! `engine` feature. Empty otherwise.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(improper_ctypes)]
#![allow(clippy::all)]
#![allow(clippy::undocumented_unsafe_blocks)]
#![allow(unsafe_code)]
#![allow(unsafe_op_in_unsafe_fn)]
#![allow(unnecessary_transmutes)]
#![allow(dead_code)]

#[cfg(target_os = "linux")]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
