# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Firmware Uno

on:
  push:
    branches: [ main, dev, fw-main ]
  pull_request:
    branches: [ main, dev, fw-main ]
  merge_group:
    branches: [ main, dev, fw-main ]
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # Daily at midnight PST (8 AM UTC)

env:
  CARGO_TERM_COLOR: always
  CACHE_KEY_ID: dd2c2bcffcf0cd62b538fdeaa31c7b89c4d42815

jobs:
  build_ubuntu:

    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: fw/plat/uno

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Restore Cargo cache
      id: cargo-cache
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.environment }}-${{ runner.os }}-${{ runner.arch }}-cargo-${{ env.CACHE_KEY_ID }}

    - name: Setup
      if: steps.cargo-cache.outputs.cache-hit != 'true' 
      run: cargo xtask precheck --setup

    - name: Add required cross-compilation targets
      if: steps.cargo-cache.outputs.cache-hit == 'true'
      run: |
        rustup target add thumbv7em-none-eabi
        rustup +nightly target add thumbv7em-none-eabi

    - name: Install nightly rustfmt
      if: steps.cargo-cache.outputs.cache-hit == 'true'
      run: cargo xtask rustup-component-add --component rustfmt --toolchain nightly

    - name: Install clippy
      if: steps.cargo-cache.outputs.cache-hit == 'true'
      run: cargo xtask rustup-component-add --component clippy

    - name: Install nightly clippy
      if: steps.cargo-cache.outputs.cache-hit == 'true'
      run: cargo xtask rustup-component-add --component clippy --toolchain nightly

    - name: Install nightly rust-src
      if: steps.cargo-cache.outputs.cache-hit == 'true'
      run: cargo xtask rustup-component-add --component rust-src --toolchain nightly

    - name: Run reggen check
      run: cargo xtask precheck --reggen

    - name: Run fmt check
      run: cargo xtask precheck --fmt

    - name: Run clippy check
      run: cargo xtask precheck --clippy

    - name: Run copyright check
      run: cargo xtask precheck --copyright

    - name: Run audit
      run: cargo xtask precheck --audit

    - name: Run build
      run: cargo xtask precheck --build
